# Generated by Django 4.2.7 on 2023-12-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Auther_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Book_Photo', models.ImageField(blank=True, null=True, upload_to='photes/Book_photes/%y/%m%d')),
                ('Auther_Photo', models.ImageField(blank=True, null=True, upload_to='photes/Auther_photes/%y/%m%d')),
                ('Pages', models.IntegerField(blank=True, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('States', models.CharField(blank=True, choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Sold', 'Sold')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MyApp.category')),
            ],
        ),
    ]
